{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-immunedeconv
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.1.1"

source:
  path: immune_deconvolution_methods

  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr, rmarkdown, shiny
requirements:
  build:
    - r-base =3.4.1
    - r-rlang =0.2.0
    - r-devtools =1.13
    - r-dplyr =0.7.4
    - r-magrittr =1.5
    - r-readr =1.1
    - r-readxl =1.0
    - r-testit =0.7
    - r-r.methodss3 =1.7
    - r-data.tree =0.7
    - r-e1071 =1.6
    - bioconductor-biocinstaller =1.28.0
    - bioconductor-biobase =2.38
    - bioconductor-preprocesscore =1.40
    - bioconductor-gsva =1.26
    - bioconductor-sva =3.26
    - bioconductor-gseabase =1.40
    - r-xcell =1.12
    - r-epic =1.1
    - r-mcpcounter =a79614e
    - r-roxygen2 =6.0.1
    - r-limsolve =1.5.5.3
    - posix               # [win]
    - {{native}}toolchain # [win]

  run:
    - r-base >=3.4.1
    - r-rlang >=0.2.0
    - r-dplyr >=0.7.4
    - r-magrittr >=1.5
    - r-readr >=1.1
    - r-readxl >=1.0
    - r-testit >=0.7
    - r-r.methodss3 >=1.7
    - r-data.tree >=0.7
    - r-e1071 >=1.6
    - bioconductor-biocinstaller >=1.28.0
    - bioconductor-biobase >=2.38
    - bioconductor-preprocesscore >=1.40
    - bioconductor-gsva >=1.26
    - bioconductor-sva >=3.26
    - bioconductor-gseabase >=1.40
    - r-xcell >=1.12
    - r-epic >=1.1
    - r-mcpcounter
    - r-roxygen2 >=6.0.1
    - r-limsolve >=1.5.5.3

test:
  commands:
    - $R -e "library('immunedeconv')" # [not win]

about:
  home: https://github.com/grst/immune_deconvolution_methods
  license: BSD 3-clause
  summary: collection of methods for immune cell deconvolution from bulk RNA-seq samples.
  license_family: BSD

