{% set version = '1.0.0' %}

package:
  name: r-immunedeconv
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/grst/immunedeconv/archive/v1.0.1.tar.gz
  sha256: 306d6288cf6cf1ddc6ec3c7449f5941da4951ad529c59c45799e98c1cd6ada53

build:
  number : 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - zip

  host:
    - r-base =3.4.1
    - r-rlang =0.2.0
    - r-devtools =1.13
    - r-dplyr =0.7.4
    - r-magrittr =1.5
    - r-readr =1.1
    - r-readxl =1.0
    - r-testit =0.7
    - r-r.methodss3 =1.7
    - r-data.tree =0.7
    - r-e1071 =1.6
    - bioconductor-biocinstaller =1.28.0
    - bioconductor-biobase =2.38
    - bioconductor-preprocesscore =1.40
    - bioconductor-gsva =1.26
    - bioconductor-sva =3.26
    - bioconductor-gseabase =1.40
    - r-xcell =1.12
    - r-epic =1.1
    - r-mcpcounter =a79614e
    - r-roxygen2 =6.0.1
    - r-limsolve =1.5.5.3
    - posix               # [win]
    - {{native}}toolchain # [win]

  run:
    - r-base >=3.4.1
    - r-rlang >=0.2.0
    - r-dplyr >=0.7.4
    - r-magrittr >=1.5
    - r-readr >=1.1
    - r-readxl >=1.0
    - r-testit >=0.7
    - r-r.methodss3 >=1.7
    - r-data.tree >=0.7
    - r-e1071 >=1.6
    - bioconductor-biocinstaller >=1.28.0
    - bioconductor-biobase >=2.38
    - bioconductor-preprocesscore >=1.40
    - bioconductor-gsva >=1.26
    - bioconductor-sva >=3.26
    - bioconductor-gseabase >=1.40
    - r-xcell >=1.12
    - r-epic >=1.1
    - r-mcpcounter
    - r-roxygen2 >=6.0.1
    - r-limsolve >=1.5.5.3

test:
  commands:
    - $R -e "library('immunedeconv')" # [not win]

about:
  home: https://github.com/grst/immune_deconvolution_methods
  license: BSD 3-clause
  summary: collection of methods for immune cell deconvolution from bulk RNA-seq samples.
  license_family: BSD

